# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2750cf58d5191bfd4b363ba6b30e6af21fab507c7a0111d468c47ca55db62356958f98036d74338ea8f5a566fbb94cc7bdd136a284b2194baae97c37fc2cec01

test:
  secret_key_base: 87e631111964618fb2e6cb3f71367a38bdaf7dc5f761bbf58194a7237044aa20f793637e4b6d661995d077b94fcb51595135f5550d6b9518d6b852fdf04dd951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
